### ISSUE TITLE
1.13 Checklist

### ISSUE THREAD

**Issue by Nathat23** [Nathat23/StackMob-2#85]
- [ ] Remove compatibility code.

- [ ] Update languages file for new entities.

- [ ] Convert back to using HashMaps rather than using metdata.

- [ ] Use Apache Commons StringUtils replace on TagTask rather than Java inbuilt.

- [ ]  Remove 1.8 getEntity compatibility method.

- [ ] Remove  use of depreciated methods.
